import { existsSync } from 'node:fs';
import type { Database } from 'bun:sqlite';

import {
  aggregateSessionPerformance, buildAggregateObservation, filterSessions, listSessionlessRuns,
  listSessionPerformance, listSessions, loadUsageForTraceTarget, runMessageTraceFromRow, traceSession,
  type ListFilterOptions, type PostgresClient,
} from './data.js';
import {
  buildMilestones, buildRunTreeEntries, buildTraceAggregateReport, buildTraceDiagnostics,
  buildTimeline, collectFocusedRunIds, filterReportForFocusedRun, summarizePerformance,
  summarizeTrace, totalStepsFromSnapshotSummaries,
} from './report.js';
import type {
  CliOptions, DelegateRow, PlanRow, RootRun, RunMessageTrace, RunSnapshotSummary,
  SessionListItem, SessionPerformanceListItem, SessionUsageSummary, SessionlessRunListItem,
  TraceAggregateReport, TraceReport, TraceRow, UsageSummary,
} from './types.js';

export interface TraceReader {
  trace(options: CliOptions): Promise<TraceReport>;
  usage(options: CliOptions): Promise<SessionUsageSummary>;
  listSessions(options?: ListFilterOptions & { recoverAgentRunSessionIds?: boolean }): Promise<SessionListItem[]>;
  listPerformance(options?: ListFilterOptions): Promise<SessionPerformanceListItem[]>;
  aggregate(options: ListFilterOptions & { groupBy: NonNullable<CliOptions['groupBy']> }): Promise<TraceAggregateReport>;
  listSessionless(): Promise<SessionlessRunListItem[]>;
  close(): Promise<void>;
}

export class TraceService {
  constructor(readonly reader: TraceReader) {}
  trace(options: CliOptions) { return this.reader.trace(options); }
  usage(options: CliOptions) { return this.reader.usage(options); }
  listSessions(options?: ListFilterOptions & { recoverAgentRunSessionIds?: boolean }) { return this.reader.listSessions(options); }
  listPerformance(options?: ListFilterOptions) { return this.reader.listPerformance(options); }
  aggregate(options: ListFilterOptions & { groupBy: NonNullable<CliOptions['groupBy']> }) { return this.reader.aggregate(options); }
  listSessionless() { return this.reader.listSessionless(); }
  close() { return this.reader.close(); }
}

export class PostgresTraceReader implements TraceReader {
  constructor(private readonly client: PostgresClient, private readonly end?: () => Promise<void>) {}
  trace(options: CliOptions) { return traceSession(this.client, options); }
  usage(options: CliOptions) { return loadUsageForTraceTarget(this.client, options); }
  listSessions(options = {}) { return listSessions(this.client, options); }
  listPerformance(options = {}) { return listSessionPerformance(this.client, options); }
  aggregate(options: ListFilterOptions & { groupBy: NonNullable<CliOptions['groupBy']> }) { return aggregateSessionPerformance(this.client, options); }
  listSessionless() { return listSessionlessRuns(this.client); }
  async close() { await this.end?.(); }
}

type Json = Record<string, any>;
type DbRun = { id: string; session_id: string | null; root_run_id: string; record_json: string };

export class SqliteTraceReader implements TraceReader {
  private readonly db: Database;
  constructor(readonly path: string) {
    if (!existsSync(path)) throw new Error(`SQLite runtime database does not exist: ${path}`);
    const { Database } = require('bun:sqlite') as typeof import('bun:sqlite');
    this.db = new Database(path, { readonly: true, strict: true });
    try { this.db.exec('PRAGMA query_only=ON'); this.validate(); }
    catch (error) { this.db.close(); throw error; }
  }
  private validate() {
    let rows: Array<{ version: number; name: string }>;
    try { rows = this.db.query('select version, name from adaptive_agent_migrations order by version').all() as typeof rows; }
    catch (e) { throw new Error(`Unsupported SQLite runtime schema in ${this.path}: adaptive_agent_migrations is missing (${message(e)}).`); }
    if (!rows.some(r => r.version === 1 && r.name === 'core:001_runtime_sqlite')) throw new Error(`Unsupported SQLite runtime schema in ${this.path}: core:001_runtime_sqlite version 1 is not installed.`);
    if (rows.some(r => r.version > 1)) throw new Error(`Unsupported newer SQLite runtime schema in ${this.path}: version ${Math.max(...rows.map(r => r.version))}.`);
    for (const table of ['agent_runs','agent_events','run_snapshots','tool_executions','plans','plan_executions']) {
      if (!this.db.query("select name from sqlite_master where type='table' and name=?").get(table)) throw new Error(`Unsupported SQLite runtime schema in ${this.path}: required table ${table} is missing.`);
    }
  }
  private tx<T>(fn: () => T): T { this.db.exec('BEGIN'); try { const out = fn(); this.db.exec('COMMIT'); return out; } catch (e) { if (this.db.inTransaction) this.db.exec('ROLLBACK'); throw e; } }
  private allRuns(): Array<DbRun & { record: Json }> { return (this.db.query('select id, session_id, root_run_id, record_json from agent_runs').all() as DbRun[]).map(r => ({...r, record: parse(r.record_json,'agent_runs',r.id,'record_json')})); }
  private roots(options: CliOptions, runs: ReturnType<SqliteTraceReader['allRuns']>) {
    if (options.sessionId) {
      if (options.rootRunId) return runs.some(r => effectiveSessionId(r) === options.sessionId && r.root_run_id === options.rootRunId) ? [options.rootRunId] : [];
      const roots = [...new Set(runs.filter(r => effectiveSessionId(r) === options.sessionId).map(r => r.root_run_id))];
      return roots.sort((left,right)=>{const a=runs.find(run=>run.id===left)?.record.createdAt??'',b=runs.find(run=>run.id===right)?.record.createdAt??'';return a.localeCompare(b)||left.localeCompare(right);});
    }
    const id = options.rootRunId ?? options.runId; if (!id) return [];
    const run = runs.find(r => r.id === id); return run ? [run.root_run_id] : [];
  }
  private rows(rootIds: string[], label: string, runs: ReturnType<SqliteTraceReader['allRuns']>): TraceRow[] {
    const selected = runs.filter(r => rootIds.includes(r.root_run_id)); const byId = new Map(runs.map(r => [r.id,r.record]));
    const events = this.db.query(`select id,run_id,seq,step_id,tool_call_id,event_type,payload_json,created_at from agent_events where run_id in (${marks(selected.length)}) order by created_at,seq`).all(...selected.map(r=>r.id)) as Json[];
    const tools = this.db.query(`select run_id,tool_call_id,child_run_id,record_json from tool_executions where run_id in (${marks(selected.length)})`).all(...selected.map(r=>r.id)) as Json[];
    const toolMap = new Map(tools.map(t => [`${t.run_id}:${t.tool_call_id}`, parse(t.record_json,'tool_executions',`${t.run_id}/${t.tool_call_id}`,'record_json')]));
    const make = (r: typeof selected[number], e?: Json): TraceRow => { const x=r.record, p=e?parse(e.payload_json,'agent_events',e.id,'payload_json'):null, t=e?toolMap.get(`${r.id}:${e.tool_call_id}`):undefined; const childId=t?.childRunId ?? p?.childRunId ?? null, child=childId?byId.get(childId):undefined; const u=x.usage??{}; return {
      session_id:r.session_id??label, root_run_id:r.root_run_id, run_id:r.id, parent_run_id:x.parentRunId??null,parent_step_id:x.parentStepId??null,run_delegate_name:x.delegateName??null,delegation_depth:x.delegationDepth??0,run_status:x.status??null,current_step_id:x.currentStepId??null,current_child_run_id:x.currentChildRunId??null,goal:x.goal??null,run_error_code:x.error?.code??x.errorCode??null,run_error_message:x.error?.message??x.errorMessage??null,run_created_at:x.createdAt??null,run_updated_at:x.updatedAt??null,run_completed_at:x.completedAt??null,total_prompt_tokens:u.promptTokens??0,total_completion_tokens:u.completionTokens??0,total_reasoning_tokens:u.reasoningTokens??0,estimated_cost_usd:u.estimatedCostUSD??0,model_provider:x.modelProvider??null,model_name:x.modelName??null,run_result:x.result??null,run_lease_owner:x.leaseOwner??null,run_lease_expires_at:x.leaseExpiresAt??null,run_heartbeat_at:x.heartbeatAt??null,event_id:e?.id??null,event_seq:e?.seq??null,event_created_at:e?.created_at??null,event_type:e?.event_type??null,event_step_id:e?.step_id??null,tool_call_id:e?.tool_call_id??null,payload:p,event_tool_name:p?.toolName??null,resolved_input:t?.input??p?.input??null,ledger_tool_name:t?.toolName??null,tool_execution_status:t?.status??null,tool_started_at:t?.startedAt??null,tool_completed_at:t?.completedAt??null,tool_output:t?.output??null,tool_error_code:t?.error?.code??t?.errorCode??null,tool_error_message:t?.error?.message??t?.errorMessage??null,child_run_id:childId,child_run_status:child?.status??null,child_error_code:child?.error?.code??child?.errorCode??null,child_error_message:child?.error?.message??child?.errorMessage??null,child_run_result:child?.result??null}; };
    return selected.flatMap(r => { const es=events.filter(e=>e.run_id===r.id); return es.length?es.map(e=>make(r,e)):[make(r)]; });
  }
  async trace(options: CliOptions): Promise<TraceReport> { return this.tx(() => { const runs=this.allRuns(), roots=this.roots(options,runs), rows=this.rows(roots,options.sessionId??options.rootRunId??options.runId??'sqlite',runs); const rootRuns=roots.map(id=>toRoot(runs.find(r=>r.id===id)!)); const snapshots=this.snapshots(roots,runs); const delegates=this.delegates(roots,runs); const plans=options.includePlans?this.plans(roots,runs):[]; const timeline=buildTimeline(rows,{onlyDelegates:options.onlyDelegates}); const warnings=['SQLite runtime traces have no gateway session metadata or separate LLM request history. Messages are reconstructed from persisted snapshots. External tool provider accounting is unavailable.']; if(!roots.length)warnings.push(options.sessionId?`Session "${options.sessionId}" was not found.`:options.runId?`Run "${options.runId}" was not found.`:`Root run "${options.rootRunId}" was not found.`); const target = options.sessionId ? {kind:'session' as const,requestedId:options.sessionId,...(options.rootRunId?{resolvedRootRunId:options.rootRunId}:{})} : options.runId ? {kind:'run' as const,requestedId:options.runId,resolvedRootRunId:roots[0]} : {kind:'root-run' as const,requestedId:options.rootRunId!,resolvedRootRunId:roots[0]}; const session=options.sessionId?sessionOverview(options.sessionId,runs):null; let report:TraceReport={target,session,rootRuns,usage:this.usageFor(roots,runs),performance:summarizePerformance(rows),timeline,milestones:buildMilestones(rows),llmMessages:options.messages||options.systemOnly||options.view==='messages'?this.messages(roots,runs,Boolean(options.reasoning)):[],runTree:buildRunTreeEntries(rows),snapshotSummaries:snapshots,totalSteps:totalStepsFromSnapshotSummaries(snapshots),delegates,plans,summary:summarizeTrace(session,rootRuns,timeline,delegates),warnings}; let diagnosticRows=rows; if(options.focusRunId){const focused=collectFocusedRunIds(report.runTree??[],options.focusRunId);if(!focused.size)warnings.push(`Run "${options.focusRunId}" was not found in the traced run tree.`);else{report=filterReportForFocusedRun(report,focused);report.summary=summarizeTrace(report.session,report.rootRuns,report.timeline,report.delegates);report.totalSteps=totalStepsFromSnapshotSummaries(report.snapshotSummaries??[]);diagnosticRows=rows.filter(row=>focused.has(row.run_id));report.performance=summarizePerformance(diagnosticRows);}} report.diagnostics=buildTraceDiagnostics(report,diagnosticRows); return report; }); }
  async usage(options: CliOptions) { return this.tx(()=>{const r=this.allRuns();return this.usageFor(this.roots(options,r),r);}); }
  private usageFor(ids:string[],runs:ReturnType<SqliteTraceReader['allRuns']>):SessionUsageSummary { const selected=runs.filter(r=>ids.includes(r.root_run_id));const runById=new Map(selected.map(run=>[run.id,run]));const toolRows=this.db.query(`select idempotency_key,run_id,child_run_id,status,record_json from tool_executions where run_id in (${marks(selected.length)})`).all(...selected.map(run=>run.id)) as Json[];const tools=toolRows.flatMap(row=>{if(row.status!=='completed'||row.child_run_id)return[];const record=parse(row.record_json,'tool_executions',row.idempotency_key,'record_json'),projection=toolOutputUsage(record);return projection?[{...projection,rootRunId:runById.get(row.run_id)?.root_run_id??''}]:[];});const byRootRun=ids.map(rootRunId=>({rootRunId,usage:sumUsage([...selected.filter(r=>r.root_run_id===rootRunId).map(r=>r.record.usage),...tools.filter(tool=>tool.rootRunId===rootRunId).map(tool=>tool.usage)] )}));const groups=new Map<string,typeof selected>();for(const run of selected){if(!hasUsage(run.record.usage))continue;const key=`${run.record.modelProvider??'unknown'}\0${run.record.modelName??'unknown'}`;groups.set(key,[...(groups.get(key)??[]),run]);}const byProviderModel=[...groups.entries()].map(([key,group])=>{const [provider,model]=key.split('\0');return{provider:provider!,model:model!,usage:sumUsage(group.map(run=>run.record.usage)),runCount:group.length};});const toolGroups=new Map<string,typeof tools>();for(const tool of tools){const key=`${tool.provider}\0${tool.model}`;toolGroups.set(key,[...(toolGroups.get(key)??[]),tool]);}const toolOutputByProviderModel=[...toolGroups.entries()].map(([key,group])=>{const[provider,model]=key.split('\0');return{provider:provider!,model:model!,usage:sumUsage(group.map(tool=>tool.usage)),toolCallCount:group.length};});return {total:sumUsage(byRootRun.map(x=>x.usage)),byRootRun,byProviderModel,toolOutputByProviderModel}; }
  async listSessions(options: ListFilterOptions = {}) { return this.tx(()=>filterSessions(this.sessionItems(this.allRuns()),options)); }
  private sessionItems(runs:ReturnType<SqliteTraceReader['allRuns']>):SessionListItem[]{ const roots=runs.filter(r=>r.id===r.root_run_id); const groups=new Map<string,typeof roots>(); for(const r of roots){const sessionId=effectiveSessionId(r),k=sessionId??`run:${r.id}`;groups.set(k,[...(groups.get(k)??[]),r]);} return [...groups.values()].map((rs):SessionListItem=>{const ordered=[...rs].sort((a,b)=>Date.parse(a.record.createdAt)-Date.parse(b.record.createdAt));return{sessionId:effectiveSessionId(ordered[0]!),startedAt:ordered[0].record.createdAt,status:sessionStatus(ordered.map(r=>r.record.status)),goals:ordered.map(r=>({rootRunId:r.id,runId:r.id,status:r.record.status,startedAt:r.record.createdAt,completedAt:r.record.completedAt??null,goal:r.record.goal??null,linkedAt:r.record.createdAt,...classifyRun(r.record)}))};}).sort((a,b)=>Date.parse(b.startedAt)-Date.parse(a.startedAt)); }
  async listSessionless(){return this.tx(()=>this.allRuns().filter(r=>r.id===r.root_run_id&&!effectiveSessionId(r)).map(r=>({sessionId:null,rootRunId:r.id,startedAt:r.record.createdAt,completedAt:r.record.completedAt??null,status:r.record.status,goal:r.record.goal??null,...classifyRun(r.record)})).sort((a,b)=>Date.parse(b.startedAt)-Date.parse(a.startedAt)));}
  async listPerformance(options:ListFilterOptions={}) { return this.tx(()=>{const runs=this.allRuns(), allEntries=filterSessions(this.sessionItems(runs),{...options,limit:undefined}).flatMap(s=>s.goals.map(g=>({s,g}))), entries=options.limit===undefined?allEntries:allEntries.slice(0,options.limit); return entries.map(({s,g})=>({sessionId:s.sessionId,sessionStatus:s.status,rootRunId:g.rootRunId,runId:g.runId,runStatus:g.status,startedAt:g.startedAt,completedAt:g.completedAt,totalDurationMs:g.startedAt&&g.completedAt?Date.parse(g.completedAt)-Date.parse(g.startedAt):null,goal:g.goal,type:g.type,swarmRole:g.swarmRole,performance:summarizePerformance(this.rows([g.rootRunId],'performance',runs))}));}); }
  async aggregate(options:ListFilterOptions&{groupBy:NonNullable<CliOptions['groupBy']>}) { return this.tx(()=>{const runs=this.allRuns();const allEntries=filterSessions(this.sessionItems(runs),{...options,limit:undefined}).flatMap(s=>s.goals);const entries=options.limit===undefined?allEntries:allEntries.slice(0,options.limit);const observations=entries.map(g=>{const rows=this.rows([g.rootRunId],'aggregate',runs);return buildAggregateObservation(g,rows,this.usageFor([g.rootRunId],runs).total,false,this.snapshots([g.rootRunId],runs));});const report=buildTraceAggregateReport(observations,options.groupBy,options);report.notes.push('SQLite has no external tool provider accounting; provider costs are not reported.');return report;}); }
  private snapshots(ids:string[],runs:ReturnType<SqliteTraceReader['allRuns']>):RunSnapshotSummary[]{return runs.filter(r=>ids.includes(r.root_run_id)).map(r=>{const xs=this.db.query('select id,snapshot_seq,created_at,record_json from run_snapshots where run_id=? order by snapshot_seq desc').all(r.id) as Json[];const latest=xs[0], rec=latest?parse(latest.record_json,'run_snapshots',latest.id,'record_json'):null;return {rootRunId:r.root_run_id,runId:r.id,delegateName:r.record.delegateName??null,depth:r.record.delegationDepth??0,latestSnapshotSeq:latest?.snapshot_seq??null,latestSnapshotCreatedAt:latest?.created_at??null,latestStepsUsed:rec?.summary?.stepsUsed??rec?.state?.stepsUsed??null};});}
  private messages(ids:string[],runs:ReturnType<SqliteTraceReader['allRuns']>,includeReasoning=false):RunMessageTrace[]{return runs.filter(r=>ids.includes(r.root_run_id)).flatMap(r=>{const xs=this.db.query('select id,snapshot_seq,created_at,record_json from run_snapshots where run_id=? order by snapshot_seq').all(r.id) as Json[];if(!xs.length)return[];const first=parse(xs[0].record_json,'run_snapshots',xs[0].id,'record_json'),last=parse(xs.at(-1)!.record_json,'run_snapshots',xs.at(-1)!.id,'record_json');const trace=runMessageTraceFromRow({root_run_id:r.root_run_id,run_id:r.id,run_delegate_name:r.record.delegateName??null,delegation_depth:r.record.delegationDepth??0,initial_snapshot_seq:xs[0].snapshot_seq,initial_snapshot_created_at:xs[0].created_at,initial_snapshot_state:{...(first.state??{}),stepsUsed:first.summary?.stepsUsed??first.state?.stepsUsed},latest_snapshot_seq:xs.at(-1)!.snapshot_seq,latest_snapshot_created_at:xs.at(-1)!.created_at,latest_snapshot_state:{...(last.state??{}),stepsUsed:last.summary?.stepsUsed??last.state?.stepsUsed}},{includeReasoning});return trace?[trace]:[];});}
  private delegates(ids:string[],runs:ReturnType<SqliteTraceReader['allRuns']>):DelegateRow[]{const selected=runs.filter(r=>ids.includes(r.root_run_id));return selected.filter(c=>c.record.parentRunId).map(c=>{const p=selected.find(r=>r.id===c.record.parentRunId)!, last=(id:string)=>this.db.query('select event_type,created_at,payload_json from agent_events where run_id=? order by seq desc limit 1').get(id) as Json|undefined,pe=last(p.id),ce=last(c.id);return {root_run_id:c.root_run_id,parent_run_id:p.id,parent_step_id:c.record.parentStepId??null,parent_status:p.record.status,child_run_id:c.id,snapshot_delegate_name:null,snapshot_child_run_id:null,child_delegate_name:c.record.delegateName??null,child_status:c.record.status,child_parent_run_id:p.id,child_parent_step_id:c.record.parentStepId??null,child_heartbeat_at:c.record.heartbeatAt??null,child_lease_owner:c.record.leaseOwner??null,child_lease_expires_at:c.record.leaseExpiresAt??null,child_updated_at:c.record.updatedAt??null,child_completed_at:c.record.completedAt??null,child_error_code:c.record.errorCode??c.record.error?.code??null,child_error_message:c.record.errorMessage??c.record.error?.message??null,child_result:c.record.result??null,delegate_reason:delegateReason(c.record.status),parent_last_event_type:pe?.event_type??null,parent_last_event_at:pe?.created_at??null,parent_last_event_payload:pe?parse(pe.payload_json,'agent_events',`${p.id}:last`,'payload_json'):null,child_last_event_type:ce?.event_type??null,child_last_event_at:ce?.created_at??null,child_last_event_payload:ce?parse(ce.payload_json,'agent_events',`${c.id}:last`,'payload_json'):null};});}
  private plans(ids:string[],runs:ReturnType<SqliteTraceReader['allRuns']>):PlanRow[]{const selected=runs.filter(r=>ids.includes(r.root_run_id));const out:PlanRow[]=[];for(const r of selected){const es=this.db.query('select id,plan_id,attempt,status,record_json from plan_executions where run_id=? order by attempt').all(r.id) as Json[];for(const e of es){const ex=parse(e.record_json,'plan_executions',e.id,'record_json');const p=this.db.query('select id,record_json from plans where id=?').get(e.plan_id) as Json|undefined;if(!p)continue;const plan=parse(p.record_json,'plans',p.id,'record_json');const steps=plan.steps?.length?plan.steps:[null];steps.forEach((s:any,i:number)=>out.push({root_run_id:r.root_run_id,run_id:r.id,plan_execution_id:e.id,plan_execution_status:e.status,attempt:e.attempt,current_step_id:ex.currentStepId??null,current_step_index:ex.currentStepIndex??null,replan_reason:ex.replanReason??null,plan_id:p.id,plan_goal:plan.goal??null,plan_summary:plan.summary??null,step_index:s?.index??i,step_key:s?.key??s?.id??null,title:s?.title??null,tool_name:s?.toolName??null,failure_policy:s?.onFailure??null,requires_approval:s?.requiresApproval??null}));}}return out;}
  async close(){this.db.close();}
}

function parse(text:string,table:string,id:string,column:string):Json { try{return JSON.parse(text);}catch(e){throw new Error(`Invalid JSON in ${table} row ${id}, column ${column}: ${message(e)}`);}}
function message(e:unknown){return e instanceof Error?e.message:String(e);}
function marks(n:number){return n?Array(n).fill('?').join(','):`''`;}
function sumUsage(items:any[]):UsageSummary{return items.reduce((a,u)=>{u=u??{};const reasoning=Number(u.reasoningTokens??0);a.promptTokens+=Number(u.promptTokens??0);a.completionTokens+=Number(u.completionTokens??0);a.reasoningTokens=(a.reasoningTokens??0)+reasoning;a.totalTokens+=Number(u.totalTokens??(Number(u.promptTokens??0)+Number(u.completionTokens??0)+reasoning));a.estimatedCostUSD+=Number(u.estimatedCostUSD??0);return a;},{promptTokens:0,completionTokens:0,reasoningTokens:0,totalTokens:0,estimatedCostUSD:0} as UsageSummary);}
function toRoot(r:DbRun&{record:Json}):RootRun{const x=r.record;return{rootRunId:r.root_run_id,runId:r.id,invocationKind:'run',turnIndex:null,linkedAt:x.createdAt,startedAt:x.createdAt,updatedAt:x.updatedAt,completedAt:x.completedAt??null,status:x.status,goal:x.goal??null,result:x.result??null,errorCode:x.errorCode??x.error?.code??null,errorMessage:x.errorMessage??x.error?.message??null,modelProvider:x.modelProvider??null,modelName:x.modelName??null,leaseOwner:x.leaseOwner??null,leaseExpiresAt:x.leaseExpiresAt??null,heartbeatAt:x.heartbeatAt??null};}
function delegateReason(status:string){return status==='succeeded'?'returned successfully':status==='failed'?'failed':status==='cancelled'?'cancelled':['queued','planning','running'].includes(status)?'still running':'state requires manual inspection';}
function sessionStatus(statuses:string[]):string{return statuses.every(status=>status==='succeeded')?'succeeded':statuses.includes('failed')?'failed':statuses[0]??'unknown';}
function classifyRun(record:Json):{type:'run'|'chat'|'swarm'|'swarm-run';swarmRole?:'coordinator'|'worker'|'quality'|'synthesizer'}{const orchestration=record.metadata?.orchestration??{};const role=['coordinator','worker','quality','synthesizer'].includes(orchestration.role)?orchestration.role:undefined;if(orchestration.kind==='swarm'&&role==='coordinator')return{type:'swarm',swarmRole:role};if(orchestration.kind==='swarm'&&role)return{type:'swarm-run',swarmRole:role};return{type:record.metadata?.invocationMode==='chat'||record.context?.invocationMode==='chat'?'chat':'run'};}
function sessionOverview(sessionId:string,runs:Array<DbRun&{record:Json}>){const selected=runs.filter(run=>effectiveSessionId(run)===sessionId);if(!selected.length)return null;const newest=[...selected].sort((a,b)=>Date.parse(b.record.updatedAt)-Date.parse(a.record.updatedAt))[0]!;const completed=[...selected].filter(run=>run.record.completedAt).sort((a,b)=>Date.parse(b.record.completedAt)-Date.parse(a.record.completedAt))[0];return{sessionId,channelId:null,agentId:null,invocationMode:null,status:sessionStatus(selected.map(run=>run.record.status)),currentRunId:newest.id,currentRootRunId:newest.root_run_id,lastCompletedRootRunId:completed?.root_run_id??null,createdAt:new Date(Math.min(...selected.map(run=>Date.parse(run.record.createdAt)))).toISOString(),updatedAt:new Date(Math.max(...selected.map(run=>Date.parse(run.record.updatedAt)))).toISOString()};}
function effectiveSessionId(run:DbRun&{record:Json}):string|null{return run.session_id??(typeof run.record.context?.sessionId==='string'?run.record.context.sessionId:null)??(typeof run.record.metadata?.gateway?.sessionId==='string'?run.record.metadata.gateway.sessionId:null);}
function hasUsage(value:Json|undefined):boolean{return Boolean(value&&(Number(value.promptTokens??0)||Number(value.completionTokens??0)||Number(value.reasoningTokens??0)||Number(value.estimatedCostUSD??0)));}
function toolOutputUsage(record:Json):{provider:string;model:string;usage:UsageSummary}|null{const output=record.output??{},usage=output.usage;if(!usage||typeof usage!=='object')return null;const reasoning=Number(usage.reasoningTokens??usage.reasoning_tokens??usage.completionTokensDetails?.reasoningTokens??usage.completion_tokens_details?.reasoning_tokens??0);const prompt=Number(usage.promptTokens??usage.prompt_tokens??0),completion=Number(usage.completionTokens??usage.completion_tokens??0);const direct=[usage.estimatedCostUSD,usage.estimated_cost_usd,usage.costUSD,usage.cost_usd,usage.totalCostUSD,usage.total_cost_usd,usage.cost,usage.total_cost,usage.cost_details?.upstream_inference_cost].map(Number).find(value=>Number.isFinite(value)&&value!==0);const split=Number(usage.cost_details?.upstream_inference_prompt_cost??usage.cost_breakdown?.prompt_cost??0)+Number(usage.cost_details?.upstream_inference_completions_cost??usage.cost_breakdown?.completions_cost??usage.cost_breakdown?.completion_cost??0),cost=direct??(split||0);if(!prompt&&!completion&&!reasoning&&!cost)return null;return{provider:String(output.provider??usage.provider??record.input?.provider??'unknown'),model:String(output.model??usage.model??record.input?.model??'unknown'),usage:{promptTokens:prompt,completionTokens:completion,...(reasoning?{reasoningTokens:reasoning}:{}),totalTokens:prompt+completion+reasoning,estimatedCostUSD:cost}};}
