import { OrchestrationOptimisticConcurrencyError } from './in-memory-orchestration-store.js';
import type { PostgresClient, PostgresPoolClient } from './postgres-runtime-stores.js';
import type { OrchestrationExecution, OrchestrationStage, OrchestrationStore } from './types.js';

interface JsonRow { record_json: OrchestrationExecution | OrchestrationStage; }
export class PostgresOrchestrationStore implements OrchestrationStore {
  constructor(private readonly client: PostgresClient | PostgresPoolClient) {}
  async createExecution(input:Parameters<OrchestrationStore['createExecution']>[0]) { return this.transaction(async client=>{const id=input.id??crypto.randomUUID(),now=new Date().toISOString(),nodes=new Set(input.stages.map(s=>s.nodeId));if(nodes.size!==input.stages.length)throw new Error('Orchestration stage nodeIds must be unique');input.stages.flatMap(s=>s.dependencies??[]).forEach(d=>{if(!nodes.has(d))throw new Error(`Unknown stage dependency ${d}`)});const record:OrchestrationExecution={id,status:input.status??'routing',request:structuredClone(input.request),catalogFingerprint:input.catalogFingerprint,plan:structuredClone(input.plan),version:0,createdAt:now,updatedAt:now};await client.query('insert into orchestration_executions(id,status,version,created_at,updated_at,record_json) values($1,$2,0,$3,$3,$4::jsonb)',[id,record.status,now,JSON.stringify(record)]);for(const s of input.stages){const stage:OrchestrationStage={executionId:id,runId:s.runId,nodeId:s.nodeId,agentId:s.agentId,status:s.status??'queued',dependencies:[...(s.dependencies??[])],upstreamRunIds:[...(s.upstreamRunIds??[])],version:0,createdAt:now,updatedAt:now};await client.query('insert into orchestration_stages(execution_id,node_id,run_id,status,dependencies,version,created_at,updated_at,record_json) values($1,$2,$3,$4,$5::jsonb,0,$6,$6,$7::jsonb)',[id,s.nodeId,s.runId,stage.status,JSON.stringify(stage.dependencies),now,JSON.stringify(stage)]);}return structuredClone(record);}); }
  async getExecution(id:string){const r=await this.client.query<JsonRow>('select record_json from orchestration_executions where id=$1',[id]);return (r.rows[0]?.record_json as OrchestrationExecution|undefined)??null;}
  async updateExecution(id:string,patch:Partial<Pick<OrchestrationExecution,'status'>>,expectedVersion:number){const current=await this.getExecution(id);if(!current)throw new Error(`Orchestration execution ${id} not found`);if(current.version!==expectedVersion)throw new OrchestrationOptimisticConcurrencyError(`Orchestration execution ${id} version mismatch`);const now=new Date().toISOString(),status=patch.status??current.status,next={...current,...patch,version:expectedVersion+1,updatedAt:now,completedAt:['succeeded','failed','cancelled'].includes(status)?current.completedAt??now:current.completedAt};const r=await this.client.query<JsonRow>('update orchestration_executions set status=$1,version=$2,updated_at=$3,record_json=$4::jsonb where id=$5 and version=$6 returning record_json',[status,next.version,now,JSON.stringify(next),id,expectedVersion]);if(!r.rows[0])throw new OrchestrationOptimisticConcurrencyError(`Orchestration execution ${id} version mismatch`);return r.rows[0].record_json as OrchestrationExecution;}
  async listStages(id:string){const r=await this.client.query<JsonRow>('select record_json from orchestration_stages where execution_id=$1 order by node_id',[id]);return r.rows.map(x=>x.record_json as OrchestrationStage);}
  async updateStage(id:string,nodeId:string,patch:Partial<Pick<OrchestrationStage,'status'|'upstreamRunIds'>>,expectedVersion:number){return this.updateStageWith(this.client,id,nodeId,patch,expectedVersion);}
  async claimReadyStage(id:string){return this.transaction(async client=>{const execution=await client.query<{status:string}>('select status from orchestration_executions where id=$1 for update',[id]);if(!execution.rows[0])throw new Error(`Orchestration execution ${id} not found`);if(!['routing','running'].includes(execution.rows[0].status))return null;const candidate=await client.query<JsonRow>(`select s.record_json from orchestration_stages s where s.execution_id=$1 and s.status='queued' and not exists (select 1 from jsonb_array_elements_text(s.dependencies) as dependency(node_id) where not exists (select 1 from orchestration_stages u where u.execution_id=s.execution_id and u.node_id=dependency.node_id and u.status in ('succeeded','failed','skipped'))) order by s.node_id for update skip locked limit 1`,[id]);const stage=candidate.rows[0]?.record_json as OrchestrationStage|undefined;return stage?this.updateStageWith(client,id,stage.nodeId,{status:'running'},stage.version):null;});}
  private async updateStageWith(client:PostgresClient,id:string,nodeId:string,patch:Partial<Pick<OrchestrationStage,'status'|'upstreamRunIds'>>,version:number){const r=await client.query<JsonRow>('select record_json from orchestration_stages where execution_id=$1 and node_id=$2',[id,nodeId]);const current=r.rows[0]?.record_json as OrchestrationStage|undefined;if(!current)throw new Error(`Orchestration stage ${nodeId} not found`);if(current.version!==version)throw new OrchestrationOptimisticConcurrencyError(`Orchestration stage ${nodeId} version mismatch`);const now=new Date().toISOString(),status=patch.status??current.status,next={...current,...structuredClone(patch),version:version+1,updatedAt:now,startedAt:status==='running'?current.startedAt??now:current.startedAt,completedAt:['succeeded','failed','cancelled','skipped'].includes(status)?current.completedAt??now:current.completedAt};const updated=await client.query<JsonRow>('update orchestration_stages set status=$1,version=$2,updated_at=$3,record_json=$4::jsonb where execution_id=$5 and node_id=$6 and version=$7 returning record_json',[status,next.version,now,JSON.stringify(next),id,nodeId,version]);if(!updated.rows[0])throw new OrchestrationOptimisticConcurrencyError(`Orchestration stage ${nodeId} version mismatch`);return updated.rows[0].record_json as OrchestrationStage;}
  private async transaction<T>(fn:(client:PostgresClient)=>Promise<T>):Promise<T>{const pooled='connect'in this.client?await this.client.connect():this.client;try{await pooled.query('begin');const result=await fn(pooled);await pooled.query('commit');return result;}catch(e){await pooled.query('rollback');throw e;}finally{if('release'in pooled)(pooled as {release():void}).release();}}
}
