import type { Database } from 'bun:sqlite';
import { OrchestrationOptimisticConcurrencyError } from './in-memory-orchestration-store.js';
import type { OrchestrationExecution, OrchestrationStage, OrchestrationStore } from './types.js';

export interface SqliteOrchestrationExecutor { run<T>(operation: () => T | Promise<T>): Promise<T>; }
const direct: SqliteOrchestrationExecutor = { async run<T>(fn: () => T | Promise<T>) { return fn(); } };

export class SqliteOrchestrationStore implements OrchestrationStore {
  constructor(private readonly db: Database, private readonly executor: SqliteOrchestrationExecutor = direct) {}
  createExecution(input: Parameters<OrchestrationStore['createExecution']>[0]): Promise<OrchestrationExecution> {
    return this.executor.run(() => this.transaction(() => {
      const id = input.id ?? crypto.randomUUID(); const now = new Date().toISOString();
      const nodes = new Set(input.stages.map(s => s.nodeId));
      if (nodes.size !== input.stages.length) throw new Error('Orchestration stage nodeIds must be unique');
      input.stages.flatMap(s => s.dependencies ?? []).forEach(dep => { if (!nodes.has(dep)) throw new Error(`Unknown stage dependency ${dep}`); });
      const record: OrchestrationExecution = { id, status: input.status ?? 'routing', request: structuredClone(input.request), catalogFingerprint: input.catalogFingerprint, plan: structuredClone(input.plan), version: 0, createdAt: now, updatedAt: now };
      this.db.run('insert into orchestration_executions (id,status,version,created_at,updated_at,record_json) values (?,?,?,?,?,?)', [id,record.status,0,now,now,JSON.stringify(record)]);
      for (const value of input.stages) { const stage: OrchestrationStage = { executionId:id, runId:value.runId,nodeId:value.nodeId,agentId:value.agentId,status:value.status??'queued',dependencies:[...(value.dependencies??[])],upstreamRunIds:[...(value.upstreamRunIds??[])],version:0,createdAt:now,updatedAt:now }; this.persistStage(stage, true); }
      return structuredClone(record);
    }));
  }
  getExecution(id: string): Promise<OrchestrationExecution|null> { return this.executor.run(() => this.read<OrchestrationExecution>('select record_json from orchestration_executions where id=?', id)); }
  updateExecution(id:string, patch:Partial<Pick<OrchestrationExecution,'status'>>, expectedVersion:number):Promise<OrchestrationExecution> { return this.executor.run(() => { const current=this.requireExecution(id); if(current.version!==expectedVersion) throw new OrchestrationOptimisticConcurrencyError(`Orchestration execution ${id} version mismatch`); const now=new Date().toISOString(); const status=patch.status??current.status; const next={...current,...patch,version:current.version+1,updatedAt:now,completedAt:['succeeded','failed','cancelled'].includes(status)?current.completedAt??now:current.completedAt}; const result=this.db.run('update orchestration_executions set status=?,version=?,updated_at=?,record_json=? where id=? and version=?',[status,next.version,now,JSON.stringify(next),id,expectedVersion]); if(result.changes!==1) throw new OrchestrationOptimisticConcurrencyError(`Orchestration execution ${id} version mismatch`); return structuredClone(next); }); }
  listStages(id:string):Promise<OrchestrationStage[]> { return this.executor.run(() => (this.db.query('select record_json from orchestration_stages where execution_id=? order by node_id').all(id) as {record_json:string}[]).map(r=>JSON.parse(r.record_json))); }
  updateStage(id:string,nodeId:string,patch:Partial<Pick<OrchestrationStage,'status'|'upstreamRunIds'>>,expectedVersion:number):Promise<OrchestrationStage> { return this.executor.run(() => this.updateStageDirect(id,nodeId,patch,expectedVersion)); }
  claimReadyStage(id:string):Promise<OrchestrationStage|null> { return this.executor.run(() => this.transaction(() => { const execution=this.requireExecution(id); if(!['routing','running'].includes(execution.status)) return null; const stages=(this.db.query('select record_json from orchestration_stages where execution_id=? order by node_id').all(id) as {record_json:string}[]).map(r=>JSON.parse(r.record_json) as OrchestrationStage); const byNode=new Map(stages.map(s=>[s.nodeId,s])); const ready=stages.find(s=>s.status==='queued'&&s.dependencies.every(d=>['succeeded','failed','skipped'].includes(byNode.get(d)?.status??''))); return ready?this.updateStageDirect(id,ready.nodeId,{status:'running'},ready.version):null; })); }
  private updateStageDirect(id:string,nodeId:string,patch:Partial<Pick<OrchestrationStage,'status'|'upstreamRunIds'>>,version:number) { const current=this.read<OrchestrationStage>('select record_json from orchestration_stages where execution_id=? and node_id=?',id,nodeId); if(!current) throw new Error(`Orchestration stage ${nodeId} not found`); if(current.version!==version) throw new OrchestrationOptimisticConcurrencyError(`Orchestration stage ${nodeId} version mismatch`); const now=new Date().toISOString(),status=patch.status??current.status; const next={...current,...structuredClone(patch),version:version+1,updatedAt:now,startedAt:status==='running'?current.startedAt??now:current.startedAt,completedAt:['succeeded','failed','cancelled','skipped'].includes(status)?current.completedAt??now:current.completedAt}; const result=this.db.run('update orchestration_stages set status=?,version=?,updated_at=?,record_json=? where execution_id=? and node_id=? and version=?',[status,next.version,now,JSON.stringify(next),id,nodeId,version]); if(result.changes!==1) throw new OrchestrationOptimisticConcurrencyError(`Orchestration stage ${nodeId} version mismatch`); return structuredClone(next); }
  private persistStage(s:OrchestrationStage,insert=false) { if(insert)this.db.run('insert into orchestration_stages (execution_id,node_id,run_id,status,version,created_at,updated_at,record_json) values (?,?,?,?,?,?,?,?)',[s.executionId,s.nodeId,s.runId,s.status,s.version,s.createdAt,s.updatedAt,JSON.stringify(s)]); }
  private requireExecution(id:string){const value=this.read<OrchestrationExecution>('select record_json from orchestration_executions where id=?',id);if(!value)throw new Error(`Orchestration execution ${id} not found`);return value;}
  private read<T>(sql:string,...args:string[]):T|null { const row=this.db.query(sql).get(...args) as {record_json:string}|null; return row?JSON.parse(row.record_json):null; }
  private transaction<T>(fn:()=>T):T { this.db.exec('BEGIN IMMEDIATE');try{const value=fn();this.db.exec('COMMIT');return value;}catch(e){if(this.db.inTransaction)this.db.exec('ROLLBACK');throw e;} }
}
