import { createHash } from 'node:crypto';
import type { AgentRegistry, ArtifactMetadataStore, AuthorizationPolicy, Clock, IdGenerator, TransactionalServiceStore } from './ports.js';
import { IdempotencyConflictError, InvalidJobStateError, ServiceForbiddenError, ServiceNotFoundError, type AdminJobListOptions, type AgentProfileRef, type ChatRequest, type CommandKind, type ControlOptions, type IdempotencyOperation, type JobListOptions, type JsonValue, type JobKind, type JobState, type OrchestratedRunRequest, type RunRequest, type ServiceActor, type ServiceJob, type ServiceJobRequest, type SubmissionOptions, type SwarmRunRequest } from './types.js';

export interface ServiceSdkDependencies { persistence: TransactionalServiceStore; registry: AgentRegistry; authorization: AuthorizationPolicy; artifacts: ArtifactMetadataStore; clock: Clock; ids: IdGenerator }
const CONTROL_STATES: Record<Exclude<CommandKind, 'execute'>, readonly JobState[]> = {
  cancel: ['accepted','queued','running','waiting_approval','waiting_clarification'], retry: ['failed','cancelled'], recover: ['failed'], resume: ['waiting_approval','waiting_clarification','failed'], continue: ['failed','succeeded'], steer: ['running','waiting_approval','waiting_clarification'], resolve_approval: ['waiting_approval'], resolve_clarification: ['waiting_clarification']
};
export class ServiceSdk {
  constructor(private readonly deps: ServiceSdkDependencies) {}
  submitRun(actor: ServiceActor, request: RunRequest, options?: SubmissionOptions) { return this.submit(actor, 'run', normalizeFileRefs(request), [request.agentId], options); }
  submitChat(actor: ServiceActor, request: ChatRequest, options?: SubmissionOptions) { return this.submit(actor, 'chat', normalizeFileRefs(request), [request.agentId], options); }
  submitSwarmRun(actor: ServiceActor, request: SwarmRunRequest, options?: SubmissionOptions) { return this.submit(actor, 'swarm', normalizeFileRefs(request), [request.coordinatorAgentId, ...request.workerAgentIds], options); }
  submitOrchestratedRun(actor: ServiceActor, request: OrchestratedRunRequest, options?: SubmissionOptions) { return this.submit(actor, 'orchestration', normalizeFileRefs(request), [request.orchestratorAgentId, ...request.agentIds], options); }
  async getJob(actor: ServiceActor, jobId: string) { await this.authorize(actor, 'get'); return this.owned(actor, jobId); }
  async listJobs(actor:ServiceActor,options:JobListOptions={}) { await this.authorize(actor,'list');return this.deps.persistence.jobs.listOwned(actor,bounds(options)); }
  cancelJob(actor: ServiceActor, jobId: string, options?: ControlOptions) { return this.control(actor, jobId, 'cancel', undefined, options); }
  retryJob(actor: ServiceActor, jobId: string, options?: ControlOptions) { return this.control(actor, jobId, 'retry', undefined, options); }
  recoverJob(actor: ServiceActor, jobId: string, options?: ControlOptions) { return this.control(actor, jobId, 'recover', undefined, options); }
  resumeJob(actor: ServiceActor, jobId: string, options?: ControlOptions) { return this.control(actor, jobId, 'resume', undefined, options); }
  continueJob(actor: ServiceActor, jobId: string, options?: ControlOptions) { return this.control(actor, jobId, 'continue', undefined, options); }
  steerJob(actor: ServiceActor, jobId: string, guidance: string, options?: ControlOptions) { return this.control(actor, jobId, 'steer', { message: guidance }, options); }
  resolveApproval(actor: ServiceActor, jobId: string, approved: boolean, options?: ControlOptions) { return this.control(actor, jobId, 'resolve_approval', { approved }, options); }
  resolveClarification(actor: ServiceActor, jobId: string, answer: string, options?: ControlOptions) { return this.control(actor, jobId, 'resolve_clarification', { answer }, options); }
  async listEvents(actor: ServiceActor, jobId: string, afterSequence = 0, limit = 100) { await this.authorize(actor, 'listEvents'); const rows = await this.deps.persistence.events.listEventsOwned(actor, jobId, afterSequence, limit); if (!rows) throw new ServiceNotFoundError(); return rows; }
  async listArtifacts(actor: ServiceActor, jobId: string) { await this.authorize(actor, 'listArtifacts'); const rows = await this.deps.artifacts.listOwned(actor, jobId); if (!rows) throw new ServiceNotFoundError(); return rows; }
  async listAvailableArtifacts(actor:ServiceActor,limit=50,offset=0) { await this.authorize(actor,'listArtifacts');return this.deps.artifacts.listAvailableOwned(actor,clamp(limit),Math.max(0,offset)); }
  async adminOverview(actor:ServiceActor) { this.admin(actor);const value=await this.deps.persistence.admin.overview();await this.adminAudit(actor,'admin:overview');return value; }
  async adminListTenants(actor:ServiceActor) { this.admin(actor);const value=await this.deps.persistence.admin.listTenants();await this.adminAudit(actor,'admin:list_tenants');return value; }
  async adminListUsers(actor:ServiceActor,tenantId?:string,limit=50,offset=0) { this.admin(actor);const value=await this.deps.persistence.admin.listUsers(tenantId,clamp(limit),Math.max(0,offset));await this.adminAudit(actor,'admin:list_users',undefined,{tenantId:tenantId??null});return value; }
  async adminListJobs(actor:ServiceActor,options:AdminJobListOptions={}) { this.admin(actor);const value=await this.deps.persistence.jobs.listAll(bounds(options));await this.adminAudit(actor,'admin:list_jobs',undefined,{tenantId:options.tenantId??null,ownerUserId:options.ownerUserId??null});return value; }
  async adminGetJob(actor:ServiceActor,jobId:string) { this.admin(actor);const job=await this.any(jobId);await this.adminAudit(actor,'admin:get_job',jobId);return job; }
  async adminListEvents(actor:ServiceActor,jobId:string,after=0,limit=100) { this.admin(actor);await this.any(jobId);const value=await this.deps.persistence.admin.listEvents(jobId,after,clamp(limit,500));await this.adminAudit(actor,'admin:list_events',jobId);return value; }
  async adminListArtifacts(actor:ServiceActor,jobId:string) { this.admin(actor);await this.any(jobId);const value=await this.deps.artifacts.listAny(jobId);await this.adminAudit(actor,'admin:list_artifacts',jobId);return value; }
  async adminListRunLinks(actor:ServiceActor,jobId:string) { this.admin(actor);await this.any(jobId);const value=await this.deps.persistence.admin.listLinks(jobId);await this.adminAudit(actor,'admin:list_run_links',jobId);return value; }
  async adminListAudit(actor:ServiceActor,jobId:string) { this.admin(actor);await this.any(jobId);await this.adminAudit(actor,'admin:list_audit',jobId);return this.deps.persistence.audit.listForJob(jobId); }
  adminCancelJob(a:ServiceActor,j:string,o?:ControlOptions){return this.adminControl(a,j,'cancel',undefined,o)} adminRetryJob(a:ServiceActor,j:string,o?:ControlOptions){return this.adminControl(a,j,'retry',undefined,o)} adminRecoverJob(a:ServiceActor,j:string,o?:ControlOptions){return this.adminControl(a,j,'recover',undefined,o)} adminResumeJob(a:ServiceActor,j:string,o?:ControlOptions){return this.adminControl(a,j,'resume',undefined,o)} adminContinueJob(a:ServiceActor,j:string,o?:ControlOptions){return this.adminControl(a,j,'continue',undefined,o)} adminSteerJob(a:ServiceActor,j:string,v:string,o?:ControlOptions){return this.adminControl(a,j,'steer',{message:v},o)} adminResolveApproval(a:ServiceActor,j:string,v:boolean,o?:ControlOptions){return this.adminControl(a,j,'resolve_approval',{approved:v},o)} adminResolveClarification(a:ServiceActor,j:string,v:string,o?:ControlOptions){return this.adminControl(a,j,'resolve_clarification',{answer:v},o)}
  private async submit(actor: ServiceActor, kind: JobKind, request: ServiceJobRequest, agentIds: string[], options?: SubmissionOptions): Promise<ServiceJob> {
    await this.authorize(actor, `submit:${kind}`); const profiles: AgentProfileRef[] = [];
    for (const id of [...new Set(agentIds)]) { const found = await this.deps.registry.resolve(id, kind); if (!found || !found.allowedWorkloads.includes(kind)) throw new ServiceNotFoundError(); profiles.push(found.profile); }
    const requestHash = stableHash({ kind, request }); const now = this.deps.clock.now().toISOString();
    return this.deps.persistence.transaction(async tx => {
      if (options?.idempotencyKey) { const old = await tx.getIdempotency(actor, kind, options.idempotencyKey); if (old) { if (old.requestHash !== requestHash) throw new IdempotencyConflictError(); const job = await tx.getOwned(actor, old.jobId); if (!job) throw new ServiceNotFoundError(); return job; } }
      const jobId = this.deps.ids.generate(), sessionId = this.deps.ids.generate();
      const job: ServiceJob = { schemaVersion: 1, id: jobId, tenantId: actor.tenantId, ownerUserId: actor.userId, kind, state: 'accepted', sessionId, request, profiles, commandVersion: 1, processedCommandVersion: 0, pendingCommand: { kind: 'execute', version: 1, requestedAt: now }, createdAt: now, updatedAt: now };
      await tx.createJob(job); await tx.appendOutbox({ id: this.deps.ids.generate(), jobId, commandVersion: 1, command: job.pendingCommand, createdAt: now });
      if (options?.idempotencyKey) await tx.createIdempotency({ ...actor, operation: kind, key: options.idempotencyKey, requestHash, jobId, createdAt: now });
      await tx.appendAudit({ id: this.deps.ids.generate(), ...actor, jobId, action: `submit:${kind}`, occurredAt: now }); return job;
    });
  }
  private async control(actor: ServiceActor, jobId: string, kind: Exclude<CommandKind,'execute'>, payload?: JsonValue, options?: ControlOptions): Promise<ServiceJob> {
    await this.authorize(actor, kind); return this.deps.persistence.transaction(async tx => { const operation: IdempotencyOperation = `control:${kind}`; const requestHash = stableHash({ jobId, kind, payload: payload ?? null }); if (options?.idempotencyKey) { const old = await tx.getIdempotency(actor, operation, options.idempotencyKey); if (old) { if (old.requestHash !== requestHash) throw new IdempotencyConflictError(); const original = await tx.getOwned(actor, old.jobId); if (!original) throw new ServiceNotFoundError(); return original; } } const job = await tx.getOwned(actor, jobId); if (!job) throw new ServiceNotFoundError(); if (!CONTROL_STATES[kind].includes(job.state)) throw new InvalidJobStateError(job.state, kind);
      const now = this.deps.clock.now().toISOString(), version = job.commandVersion + 1; const updated = { ...job, state: kind === 'cancel' ? 'cancelling' as const : job.state, commandVersion: version, pendingCommand: { kind, version, payload, requestedAt: now }, updatedAt: now };
      if (!await tx.updateOwned(actor, updated)) throw new ServiceNotFoundError(); await tx.appendOutbox({ id: this.deps.ids.generate(), jobId, commandVersion: version, command: updated.pendingCommand, createdAt: now }); if (options?.idempotencyKey) await tx.createIdempotency({ ...actor, operation, key: options.idempotencyKey, requestHash, jobId, createdAt: now }); await tx.appendAudit({ id: this.deps.ids.generate(), ...actor, jobId, action: kind, occurredAt: now, data: payload }); return updated; });
  }
  private async adminControl(actor:ServiceActor,jobId:string,kind:Exclude<CommandKind,'execute'>,payload?:JsonValue,options?:ControlOptions) { this.admin(actor);return this.deps.persistence.transaction(async tx=>{const operation:IdempotencyOperation=`control:${kind}`,requestHash=stableHash({jobId,kind,payload:payload??null});if(options?.idempotencyKey){const old=await tx.getIdempotency(actor,operation,options.idempotencyKey);if(old){if(old.requestHash!==requestHash)throw new IdempotencyConflictError();const original=await tx.getAny(old.jobId);if(!original)throw new ServiceNotFoundError();return original;}}const job=await tx.getAny(jobId);if(!job)throw new ServiceNotFoundError();if(!CONTROL_STATES[kind].includes(job.state))throw new InvalidJobStateError(job.state,kind);const now=this.deps.clock.now().toISOString(),version=job.commandVersion+1;const updated={...job,state:kind==='cancel'?'cancelling' as const:job.state,commandVersion:version,pendingCommand:{kind,version,payload,requestedAt:now},updatedAt:now};if(!await tx.updateAny(updated))throw new ServiceNotFoundError();await tx.appendOutbox({id:this.deps.ids.generate(),jobId,commandVersion:version,command:updated.pendingCommand,createdAt:now});if(options?.idempotencyKey)await tx.createIdempotency({tenantId:actor.tenantId,userId:actor.userId,operation,key:options.idempotencyKey,requestHash,jobId,createdAt:now});await tx.appendAudit({id:this.deps.ids.generate(),tenantId:actor.tenantId,userId:actor.userId,jobId,action:`admin:${kind}`,occurredAt:now,data:payload});return updated;}); }
  private admin(actor:ServiceActor) { if(!actor.roles?.includes('platform_admin'))throw new ServiceForbiddenError(); }
  private async adminAudit(actor:ServiceActor,action:string,jobId?:string,data?:JsonValue) { await this.deps.persistence.audit.appendAudit({id:this.deps.ids.generate(),tenantId:actor.tenantId,userId:actor.userId,jobId,action,occurredAt:this.deps.clock.now().toISOString(),data}); }
  private async any(id:string) { const job=await this.deps.persistence.jobs.getAny(id);if(!job)throw new ServiceNotFoundError();return job; }
  private async authorize(actor: ServiceActor, op: string) { if (!await this.deps.authorization.authorize(actor, op)) throw new ServiceNotFoundError(); }
  private async owned(actor: ServiceActor, id: string) { const job = await this.deps.persistence.jobs.getOwned(actor, id); if (!job) throw new ServiceNotFoundError(); return job; }
}
function clamp(limit=50,max=200){return Math.max(1,Math.min(max,limit));}
function bounds<T extends JobListOptions>(o:T):T{return {...o,limit:clamp(o.limit),offset:Math.max(0,o.offset??0)};}
function stableHash(value: unknown): string { return createHash('sha256').update(JSON.stringify(sort(value))).digest('hex'); }
function sort(value: unknown): unknown { if (Array.isArray(value)) return value.map(sort); if (value && typeof value === 'object') return Object.fromEntries(Object.entries(value).sort(([a],[b]) => a.localeCompare(b)).map(([k,v]) => [k, sort(v)])); return value; }
function normalizeFileRefs<T extends ServiceJobRequest>(request:T):T { const {fileRefs,...rest}=request;return (fileRefs?.length?{...rest,fileRefs:[...new Map(fileRefs.map(ref=>[ref.artifactId.toLowerCase(),{artifactId:ref.artifactId.toLowerCase()}])).values()]}:rest) as T; }
